### ISSUE TITLE
Mobile push notifications

### ISSUE THREAD

**Issue by Minionguyjpro** [92lleo/WhatsappWebToGo#63] opened 2021-12-13 16:03 UTC
Make it possible to get mobile push notifications like you get desktop notifications on web via pc. Sorry if this already exist. I'm new here.

**Comment by 92lleo** [comment] 2021-12-13 20:22
already exists ;) 
duplicate of #4

**Closed by 92lleo** 2021-12-13 20:22 UTC

**Comment by Minionguyjpro** [comment] 2021-12-14 07:11
I saw, but will it come? I'm now using this app on my Samsung tablet so i can chat from my tablet. It would be nice to have notifications support.

**Comment by Minionguyjpro** [comment] 2021-12-14 07:11
So i know when someone sends an message without having to start the app

**Comment by 92lleo** [comment] 2021-12-14 19:54
well it comes when I have the time to do it or anyone else offers a PR. no ETAs.
