### ISSUE TITLE
Android 4.4.4

### ISSUE THREAD

**Issue by xorbettino** [92lleo/WhatsappWebToGo#1] opened 2017-12-17 18:57 UTC
On startup doesn't show qr code, it ask to use a browser.

**Comment by 92lleo** [comment] 2017-12-17 19:27
Hi, thanks for reporting this.
I could reproduce this with an 4.4.4 device. Will check.
![device-2017-12-17-202416](https://user-images.githubusercontent.com/12110344/34082976-a807037c-e368-11e7-8b48-9e9bdeae8cda.png)

**Comment by 92lleo** [comment] 2017-12-17 19:58
It looks like the webview shipped with Kitkat (4.4.4.) does not work the way it should to support whatsapp web. The problem is, that the webview was not shipped as an apk in 4.4.4 but was baked into the system, so it cannot be updated. I'll look for other ways to solve this, but it could take a while

**Comment by xorbettino** [comment] 2017-12-17 20:23
Thanx for your work,  I'll wait for a fix.

**Comment by 92lleo** [comment] 2017-12-20 20:18
Looks like there is now way getting it to work on Kitkat (4.4(.4)) devices. The next update disables the possibility to install on devices lower than 5.0 (Lollipop)
I'm sorry i couldn't fix this. I'll close this now but continue to search for a fix. Should I find something I will update this issue.

**Closed by 92lleo** 2017-12-20 20:18 UTC
Labels: bug
